// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbD0ukijAB4blZQQmmQHOJDWPi4uLw7co',
    appId: '1:625845391987:web:619e0b0d25ec380e249006',
    messagingSenderId: '625845391987',
    projectId: 'chat-9c701',
    authDomain: 'chat-9c701.firebaseapp.com',
    storageBucket: 'chat-9c701.firebasestorage.app',
    measurementId: 'G-PS1YD00LKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmQrbkh6Q9DBnD3Pimz_flbf3ZkNnufEs',
    appId: '1:625845391987:android:2213e41764709e5a249006',
    messagingSenderId: '625845391987',
    projectId: 'chat-9c701',
    storageBucket: 'chat-9c701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNNoz-FQfayqs1pPy4VxtQzkXrWXrgSbg',
    appId: '1:625845391987:ios:47fdb17c99d8191b249006',
    messagingSenderId: '625845391987',
    projectId: 'chat-9c701',
    storageBucket: 'chat-9c701.firebasestorage.app',
    iosBundleId: 'com.example.lioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNNoz-FQfayqs1pPy4VxtQzkXrWXrgSbg',
    appId: '1:625845391987:ios:47fdb17c99d8191b249006',
    messagingSenderId: '625845391987',
    projectId: 'chat-9c701',
    storageBucket: 'chat-9c701.firebasestorage.app',
    iosBundleId: 'com.example.lioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqU2q_cGLECgfAEtREh-uF2-uN9aP1loo',
    appId: '1:625845391987:web:5c48812788451dc8249006',
    messagingSenderId: '625845391987',
    projectId: 'chat-9c701',
    authDomain: 'chat-9c701.firebaseapp.com',
    storageBucket: 'chat-9c701.firebasestorage.app',
    measurementId: 'G-9VMP8J6T8K',
  );
}
