// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8-8aSSSFZSCAHy8MrlRplLfoLrA4NPBs',
    appId: '1:434169730793:web:4d86b86ebf6f31ebf28278',
    messagingSenderId: '434169730793',
    projectId: 'liova-4be39',
    authDomain: 'liova-4be39.firebaseapp.com',
    storageBucket: 'liova-4be39.firebasestorage.app',
    measurementId: 'G-28KPRBMNZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNMTrcuyL0a4P_R-jnFW1S4g_3fgu517I',
    appId: '1:434169730793:android:6d2d7ed57bf29d34f28278',
    messagingSenderId: '434169730793',
    projectId: 'liova-4be39',
    storageBucket: 'liova-4be39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrLJqGtEzoCgCOv6dMe4RYYB0Tq21uoqM',
    appId: '1:434169730793:ios:59d55fea28856db2f28278',
    messagingSenderId: '434169730793',
    projectId: 'liova-4be39',
    storageBucket: 'liova-4be39.firebasestorage.app',
    iosBundleId: 'com.example.li',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrLJqGtEzoCgCOv6dMe4RYYB0Tq21uoqM',
    appId: '1:434169730793:ios:59d55fea28856db2f28278',
    messagingSenderId: '434169730793',
    projectId: 'liova-4be39',
    storageBucket: 'liova-4be39.firebasestorage.app',
    iosBundleId: 'com.example.li',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8-8aSSSFZSCAHy8MrlRplLfoLrA4NPBs',
    appId: '1:434169730793:web:d8d26e91b30dbfe2f28278',
    messagingSenderId: '434169730793',
    projectId: 'liova-4be39',
    authDomain: 'liova-4be39.firebaseapp.com',
    storageBucket: 'liova-4be39.firebasestorage.app',
    measurementId: 'G-P3H88VV7E3',
  );
}
